
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddNewsService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/ws_addnews?wsdl")
public class AddNewsService
    extends Service
{

    private final static URL ADDNEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDNEWSSERVICE_EXCEPTION;
    private final static QName ADDNEWSSERVICE_QNAME = new QName("http://ws/", "AddNewsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws_addnews?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDNEWSSERVICE_WSDL_LOCATION = url;
        ADDNEWSSERVICE_EXCEPTION = e;
    }

    public AddNewsService() {
        super(__getWsdlLocation(), ADDNEWSSERVICE_QNAME);
    }

    public AddNewsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDNEWSSERVICE_QNAME, features);
    }

    public AddNewsService(URL wsdlLocation) {
        super(wsdlLocation, ADDNEWSSERVICE_QNAME);
    }

    public AddNewsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDNEWSSERVICE_QNAME, features);
    }

    public AddNewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNewsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddNews
     */
    @WebEndpoint(name = "AddNewsPort")
    public AddNews getAddNewsPort() {
        return super.getPort(new QName("http://ws/", "AddNewsPort"), AddNews.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddNews
     */
    @WebEndpoint(name = "AddNewsPort")
    public AddNews getAddNewsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "AddNewsPort"), AddNews.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDNEWSSERVICE_EXCEPTION!= null) {
            throw ADDNEWSSERVICE_EXCEPTION;
        }
        return ADDNEWSSERVICE_WSDL_LOCATION;
    }

}
