
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriptionUnsubscriptionService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/ws_sub_unsub?wsdl")
public class SubscriptionUnsubscriptionService
    extends Service
{

    private final static URL SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_EXCEPTION;
    private final static QName SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_QNAME = new QName("http://ws/", "SubscriptionUnsubscriptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws_sub_unsub?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_WSDL_LOCATION = url;
        SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_EXCEPTION = e;
    }

    public SubscriptionUnsubscriptionService() {
        super(__getWsdlLocation(), SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_QNAME);
    }

    public SubscriptionUnsubscriptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_QNAME, features);
    }

    public SubscriptionUnsubscriptionService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_QNAME);
    }

    public SubscriptionUnsubscriptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_QNAME, features);
    }

    public SubscriptionUnsubscriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionUnsubscriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionUnsubscription
     */
    @WebEndpoint(name = "SubscriptionUnsubscriptionPort")
    public SubscriptionUnsubscription getSubscriptionUnsubscriptionPort() {
        return super.getPort(new QName("http://ws/", "SubscriptionUnsubscriptionPort"), SubscriptionUnsubscription.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionUnsubscription
     */
    @WebEndpoint(name = "SubscriptionUnsubscriptionPort")
    public SubscriptionUnsubscription getSubscriptionUnsubscriptionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "SubscriptionUnsubscriptionPort"), SubscriptionUnsubscription.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_EXCEPTION!= null) {
            throw SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_EXCEPTION;
        }
        return SUBSCRIPTIONUNSUBSCRIPTIONSERVICE_WSDL_LOCATION;
    }

}
